// MongoDB Insert Script for NMMR Training Platform — Agentic AI Curriculum
//
// This script reads course data from seed-data.json (generated by generate-sample-courses.js)
// and inserts it into MongoDB.
//
// Before running, generate the seed data:
//   node scripts/generate-sample-courses.js
//
// Usage with Node.js (recommended):
//   DATABASE_URL=mongodb://... node scripts/seed-courses.js
//
// Or set DATABASE_URL in a .env.local file and install dotenv:
//   node -e "require('dotenv').config({path:'.env.local'})" scripts/seed-courses.js

const fs = require("fs");
const path = require("path");

// Load seed data
const seedDataPath = path.resolve(__dirname, "seed-data.json");
if (!fs.existsSync(seedDataPath)) {
  console.error(
    "ERROR: seed-data.json not found. Run 'node scripts/generate-sample-courses.js' first."
  );
  process.exit(1);
}

const courses = JSON.parse(fs.readFileSync(seedDataPath, "utf-8"));

// Add timestamps
const now = new Date();
for (const course of courses) {
  course.createdAt = now;
  course.updatedAt = now;
}

// If running in mongosh context (db is available), insert directly
if (typeof db !== "undefined") {
  // mongosh mode
  db.courses.insertMany(courses);
  print(`Successfully inserted ${courses.length} courses into the courses collection.`);
  print(`Total lessons: ${courses.reduce((a, c) => a + c.modules.reduce((b, m) => b + m.lessons.length, 0), 0)}`);
  print("Run db.courses.find().count() to verify.");
} else {
  // Node.js mode — use MongoDB driver
  const { MongoClient } = require("mongodb");

  // Try to load .env.local
  try {
    require("dotenv").config({ path: ".env.local" });
  } catch {
    // dotenv not installed, rely on environment variable
  }

  const uri = process.env.DATABASE_URL;
  if (!uri) {
    console.error("ERROR: DATABASE_URL environment variable is not set.");
    console.error(
      "Usage: DATABASE_URL=mongodb://... node scripts/seed-courses.js"
    );
    process.exit(1);
  }

  async function main() {
    const client = new MongoClient(uri);
    try {
      await client.connect();
      const db = client.db(); // uses DB from connection string
      const result = await db.collection("courses").insertMany(courses);
      console.log(`Inserted ${result.insertedCount} courses.`);
      const totalLessons = courses.reduce(
        (a, c) => a + c.modules.reduce((b, m) => b + m.lessons.length, 0),
        0
      );
      console.log(`Total lessons: ${totalLessons}`);
    } finally {
      await client.close();
    }
  }

  main().catch(console.error);
}
